import{a as L,S as w,i as a}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function g(e,r=1,o=15){const i="https://pixabay.com/api/",t=new URLSearchParams({key:"37050490-6d3dacd6192465869ce2cc708",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:o}),s=`${i}?${t}`;return(await L.get(s)).data}function v(e){return` <li class="list-item">
            <a href="${e.largeImageURL}" class="gallery-item">
              <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
            </a>
            <div class="info">
              <p>Likes: ${e.likes}</p>
              <p>Views: ${e.views}</p>
              <p>Comments: ${e.comments}</p>
              <p>Downloads: ${e.downloads}</p>
            </div>
          </li>`}function y(e){return e.map(v).join("")}const S=document.querySelector("#search-form"),h=document.querySelector("#list"),c=document.querySelector("#load-more"),d=document.querySelector(".loader");let l="",u=1,f=0,m=0;const p=new w(".gallery a",{captionsData:"alt",captionDelay:250});S.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.query.value.trim(),!l){a.error({title:"Error",message:"Please enter a search query."});return}u=1,h.innerHTML="",c.classList.add("hidden"),d.classList.remove("hidden");try{const r=await g(l,u);if(r.hits.length===0){a.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}f=r.totalHits,m=r.hits.length;const o=y(r.hits);h.innerHTML=o,p.refresh(),m<f&&c.classList.remove("hidden")}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.add("hidden")}});c.addEventListener("click",async()=>{d.classList.remove("hidden");try{u+=1;const e=await g(l,u);m+=e.hits.length;const r=y(e.hits);h.insertAdjacentHTML("beforeend",r);const{height:o}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),p.refresh(),m>=f&&(c.classList.add("hidden"),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{d.classList.add("hidden")}});
//# sourceMappingURL=commonHelpers.js.map
