import{a as y,i as l,S as L}from"./assets/vendor-ee72e1a4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();async function h(e,s=1,o=15){const n="https://pixabay.com/api/",t=new URLSearchParams({key:"37050490-6d3dacd6192465869ce2cc708",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:o}),r=`${n}?${t}`;try{return(await y.get(r)).data}catch{l.error({title:"Error",message:"Something went wrong. Please try again later."})}}function w(e){return` <li class="list-item">
            <a href="${e.largeImageURL}" class="gallery-item">
              <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
            </a>
            <div class="info">
              <p>Likes: ${e.likes}</p>
              <p>Views: ${e.views}</p>
              <p>Comments: ${e.comments}</p>
              <p>Downloads: ${e.downloads}</p>
            </div>
          </li>`}function p(e){return e.map(w).join("")}const v=document.querySelector("#search-form"),m=document.querySelector("#list"),c=document.querySelector("#load-more");let i="",d=1,f=0,u=0;v.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.target.elements.query.value.trim(),!i){l.error({title:"Error",message:"Please enter a search query."});return}d=1,m.innerHTML="",c.classList.add("hidden");const s=await h(i,d);if(s.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}f=s.totalHits,u=s.hits.length;const o=p(s.hits);m.innerHTML=o,g.refresh(),u<f&&c.classList.remove("hidden")});c.addEventListener("click",async()=>{d+=1;const e=await h(i,d);u+=e.hits.length;const s=p(e.hits);m.insertAdjacentHTML("beforeend",s),g.refresh();const{height:o}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),u>=f&&(c.classList.add("hidden"),l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))});const g=new L(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
